### ISSUE TITLE
[beta] Dragging windows from fullscreen etc not working

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#159]
When dragging windows from fullscreen or maximizing from the task bar, stuff snaps back to their previous state after releasing trigger. 
Also can't press save on the Firefox download dialog, presumably because of the same issue. 

Edit: Also worth mentioning, this was on Build 520, just noticed 524 was released.

https://user-images.githubusercontent.com/50369014/118128112-c4ce9180-b3fa-11eb-860d-c4fd0c896ae4.mp4

**Comment by Xiexe** [comment]
Seems like it's triggering a false positive on a double click, could you verify if this happens on both live and on 524?

As for Firefox, if you're talking about the download panel itself, it's actually a separate window that needs to be captured (same with standard right click menus) - this broke when I changed APIs and I'll need to fix the handling for it.

**Comment by Swingly6061** [comment]
Doesn't happen on Live, and since I'm using a desktop capture, the dialog does appear, I just can't interact with it properly.

**Comment by Xiexe** [comment]
Well, the interacting on a desktop captures not working is strange.

I downloaded a log earlier through FF on the current beta and was able to click the save button. Are you running Firefox as an elevated application? (Doubt it since you can interact with it)

Beta 520 was kind of really broken, though, so I wouldn't be surprised if it's just an issue on 520.

I'll look into the false double click and see if I can recreate it tomorrow when I'm working.

**Comment by Swingly6061** [comment]
Yeah just tested 524, works fine. 
Guess I'll close this then. xD
