### ISSUE TITLE
[SQU-314] [FEEDBACK] Add option to restore functionality of 'Block Input to Background Apps' back to previous behaviour

### ISSUE THREAD

**Issue by SalbugVR** [Xiexe/XSOverlay-Issue-Tracker#274]
> - Input Blocking now only blocks inputs when hovering on an overlay, rather than while in Layout Mode. This means you can now quickly go back and forth between interacting with your game and the overlay without disabling layout mode.

While I can see why this feature was adjusted this way, I'd much prefer if functionality was reverted back to how it was before Build 614. It was useful in preventing myself from accidently clicking anything while in my overlay, but now even with it on, I find myself doing it too often now by accident.

<sub>[SQU-314](https://linear.app/square-hole-interactive/issue/SQU-314/[feedback]-add-option-to-restore-functionality-of-block-input-to)</sub>

**Comment by LoganDark** [comment]
should be a config setting for sure (both options should exist)

**Comment by The-PC** [comment]
logged in to post this same issue, since it went live <.<

Currently if you hover on an overlay, it holds the previous input in app whether you're in layout mode or not. 

Previous (desired) behavior was that layout mode blocks inputs whether hovering over an overlay or not, and needed a click for the mouse to start registering location/input. Was a good buffer for accidental clicks or mouse movements. Outside of layout mode, it never blocked inputs to app, and still required that click before registering mouse location/input. That initial click would reset when hovering off the window regardless of layout mode. Switching from non layout mode to layout mode would hold previous input in app. All desired behavior imo
It did have one issue where opening the steamvr menu would allow inputs while in layout mode, but could be fixed by toggling out and back into layout

**Comment by Xiexe** [comment]
Yeah, the holding the last input thing is unfortunately a SteamVR limitation. The toggle is planned and wont be too long before it gets updated, dont worry.

**Comment by The-PC** [comment]
the update doesn't seem to resolve this, it does hold the previous input in app when opening layout mode, but it doesn't seem to reintroduce that mouse buffer click. It sort of does the buffer click when one opposite hand is hovering over the keyboard, but that seems to just be switching hands pretty much. Nothing is different when not in layout mode. 

Heh I dunno, maybe this is a feature request at this point because it didn't seem to be the original intention of the toggle anyway, even though it was previous behavior

**Comment by Xiexe** [comment]
Mouse buffer click comes from a different setting called "Automatic Mouse Control", having it off is the setting you'll want to change for that, unrelated to input blocking.

**Comment by The-PC** [comment]
ah yeah you're totally right, could have sworn I had that toggled off, but the first big update switched it back on I guess, thanks heh
I definitely was confused and associating the two
