### ISSUE TITLE
[SQU-317] UI on left wrist despite setting

### ISSUE THREAD

**Issue by yewnyx** [Xiexe/XSOverlay-Issue-Tracker#299]
**Describe the bug in detail:**
I launch XSO with the UI on my right wrist. Launched XSO today, and after thinking it failed to launch, discovered the UI on left wrist (this survived two XSO restarts so I presume it wasn't a transient issue). However, upon opening the menu, toggling dominant wrist didn't move the UI. I tried toggling it twice but it remained on my left wrist.

**Provide steps to reproduce the bug:**
* Launch XSO and observe UI is on left wrist.
* In my case, I had it on my right wrist in the previous beta and then updated and launched the latest beta, where it was stuck on the left, if that matters (i.e. serialization differences between versions)

**Expected behavior:**
What do you expect to happen, rather than what does happen?
* XSO obeys the wrist setting

<sub>[SQU-317](https://linear.app/square-hole-interactive/issue/SQU-317/ui-on-left-wrist-despite-setting)</sub>

**Comment by sli** [comment]
Just want to add that this has been an issue for me since at least RC3.1. I can't confirm any earlier, as that was when I originally switched to the beta branch.

**Comment by Xiexe** [comment]
Me wondering why you never reported it if it's been an issue for that long.....

**Comment by sli** [comment]
Because the stakes are not that high? I came back to revise my comment to mention that the current release version works, since I hadn't used it since last weekend when I tried RC3.1 for a handful of minutes and deciding I wasn't going to troubleshoot it at 1AM on a Saturday. I had swapped to release last weekend, but was on the beta branch tonight when I launched Steam, so there was some minor confusion on my part when I originally commented. Sorry for that.

So whatever seems to be causing the issue, in my case it's been localized to the beta branches released to Steam and not just the newer codebase in general.

**Comment by Xiexe** [comment]
I was mostly joking around, it's fine.

I just find it silly when someone comes along and says "I've had this bug for a year!"  (exaggerating, but I've actually had people say very long periods of time) without reporting it. Obviously going from RC3 to Release isn't a long period of time, that stuff moved pretty quick, so I was mostly just poking at you about it.

**Comment by Xiexe** [comment]
Fixed in 629
https://store.steampowered.com/news/app/1173510/view/3731854112026877505
