### ISSUE TITLE
CPU usage showing as 250% or more

### ISSUE THREAD

**Issue by AxionHusky** [Xiexe/XSOverlay-Issue-Tracker#317]
Hello!

I took a long hiatus from VRChat and recently decided to get back into it. I purchased a new headset (Meta Quest 2) as well as a RTX 4070. No other PC components have changed. (previously did not experience this issue).

Since fitting the new GPU, my CPU usage displays as over 250% at all times on XS. When checking CPU usage in task manager, it's only sitting at around 10%. Whilst it's not a critical issue, it would be nice to have my CPU usage displayed correctly.

Haven't been able to work out how to fix it. Log attatched.

Thank you.

[output_log_2024-01-24__22.39.32.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/14075377/output_log_2024-01-24__22.39.32.txt)

**Comment by PoptartGhost** [comment]
its almost always said this for me, ive wondered since start if maybe its ment to read some other kind of useage?

Like perhaps its allocating threads into its overall % somehow and xie just hasnt explained this in the setup ? 

I have programs that run 800 threads (ik crazy) and they would definatly be more than the cpus 100% if calculated maybe?

**Comment by Xiexe** [comment]
This should be fixed on beta branch!
