### ISSUE TITLE
Only right thumbstick works for scrolling (Index)

### ISSUE THREAD

**Issue by Swingly6061** [Xiexe/XSOverlay-Issue-Tracker#55]
A clear and concise description of what the bug is:
Left thumbstick doesn't scroll pages.

Always behaves like this.

What do you expect to happen, rather than what does happen?
I mainly use my left hand for pointing and such so I expect the scroll function to be on both controllers.

[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/4397891/output_log.txt)

**Comment by Xiexe** [comment]
The right joystick works for scrolling due to a lot of games utilizing the left joystick for movement, and the right joystick for turning (left and right) but not using the up and down of that joystick. 

You can bind the scroll to the other joystick in the bindings page and everything should work fine.

**Comment by Swingly6061** [comment]
Ah, I see. Thanks for explaining that.

**Comment by Xiexe** [comment]
Closing this issue as I believe it's solved!
