### ISSUE TITLE
add chroma key option for windows

### ISSUE THREAD

**Issue by cubedparadox** [Xiexe/XSOverlay-Issue-Tracker#71]
**Feature Description:**
Similar to the transparent desktop background request, it'd be cool to be able to color pick and make the background of any reasonably colored application transparent.

**Comment by Xiexe** [comment]
Would be neat, but since we don't use cameras for our desktop and window capture overlay textures, it may be hard to do without significant performance overhead. 

I'd like to look into getting a darkening filter working first, and then depending on that, the solution may also work for chroma keying out stuff.

**Comment by Xiexe** [comment]
Unable to add this due to limitations of how we're currently rendering windows. This may be something that we can support with the new API's once they're done, closing for now, though. 

Will revisit in the future.
