### ISSUE TITLE
XSOverlay isn't working

### ISSUE THREAD

**Issue by 486dx33mhz** [Xiexe/XSOverlay-Issue-Tracker#90]
Title, XSOverlay isn't picking up the amount of controllers/trackers connected (on Oculus). Won't let me add any windows to my wrist, it's just stuck at a small size with the time and date on, and the buttons for settings etc above the time and date aren't visible. Tried reinstalling, restarting xsoverlay, steamvr, and my pc and it's still happening.

**Comment by Xiexe** [comment]
Please refer to this announcement made awhile back due to bindings changes.

https://steamcommunity.com/games/1173510/announcements/detail/4119055961243467398

If you do not see the default bindings when following this, create a new binding, save it, and then delete it.
The default should show up after that.

This is a bug on SteamVRs end and the only workaround I'm aware of, currently.

**Comment by Xiexe** [comment]
Closing issue for now due to inactivity!
