### ISSUE TITLE
Keyboard sometimes disappears when trying to move it (settings does too).

### ISSUE THREAD

**Issue by FEFELAND** [Xiexe/XSOverlay-Issue-Tracker#93]
**Describe the bug in detail:**
Sometimes (not always) when I try to grab the keyboard to move it, it just disappears. This also applies to the settings window. Desktop windows and moving the wrist seem to not have this issue.
Video: https://streamable.com/84pfxa

**Provide steps to reproduce the bug:**
I'm not entirely sure... On some boots it does it.. On others, it works fine.

**Expected behavior:**
Just the normal action of being able to reposition the keyboard or settings screen.

**Output Log:**
You can find your output log at `C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\`
You can find the uWindowCapture and uDesktopCapture 
log in the XSOverlay install directory.
Please attach your logs to the issue.
[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5256384/output_log.txt)
[uWindowCapture.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5256392/uWindowCapture.log)
[uDesktopDuplication.log](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5256402/uDesktopDuplication.log)

**Comment by Xiexe** [comment]
Could you please provide your config? I'll load it up locally and see if I can't recreate and fix this! I have a feeling this is due to the Aim At Target option, or something else to do with some option. 

I watched your video, and that's currently where the trial is leading to! 
The config file is located in 

`C:\Users\[Username]\AppData\LocalLow\Xiexe\XSOverlay\config\overlaySettings.json`

You may also have a `.xs` file there if you've used an old version of the overlay, prior to the UI changes, you can ignore or delete that if it exists. I only want the `.json` file.

**Comment by FEFELAND** [comment]
Yup found them.
Uhh.. github doesn't like the file so... here's puush: https://puu.sh/GuXtg/f63d946603.json

I've now deleted the .xs file too.

PS:
(unfortunately I can't test or retest things btw... my index is having issues with booting up and can only get it to work a single time after I hit "remove steamvr drivers" [and doesn't always work] in the dev settings for SteamVR)

**Comment by Xiexe** [comment]
All good, I'll take a look at this when I get off of break this week, thank you! :)

I'll keep you updated on the issue!

**Comment by Xiexe** [comment]
Just wanted to let you know, I've figured out what the problem is - I will hopefully have a fix in this next wave of beta releases prior to them going to the Live branch.

**Comment by FEFELAND** [comment]
Oh nice! Thanks for the update!
I was actually wondering if something had changed already since I noticed the following:
Whenever the keyboard "disappeared", all I had to do was sort of keep holding and rotate my hand around. In a singe frame, the keyboard would flip making me see it from the back side and thus, appear gone, when.. it wasn't.  (Unsure if it was the same case for the settings menu).

**Comment by Xiexe** [comment]
Yeah, the issue in particular is something to do with having the window movement set so that it doesn't aim at any particular target.

It's basically an amplified problem of what happens when you grab the wrist overlay, where it snaps to some random position instead of staying in the same spot.

I'll need to change a few things with how window movement works to get this working properly.

**Comment by Xiexe** [comment]
Fixed this in the upcoming release!
