### ISSUE TITLE
Occasionally all inputs get blocked from the game

### ISSUE THREAD

**Issue by Macil** [Xiexe/XSOverlay-Issue-Tracker#96]
About once a day while playing in VR with XSOverlay active, at some point the game becomes unresponsive to controller buttons and joysticks. The game still responds to the controllers' positions and finger tracking, but the game no longer responds to me pressing buttons on the controller, including trigger, B, A, or the joystick.

When this happens, I'm still able to open and close the steamvr dashboard, and both the steamvr dashboard and XSOverlay still work fine and respond to controller inputs. I can interact with either or open and close the steamvr dashboard, but the game stays unresponsive to inputs. Closing or launching a game does not fix the issue; the issue persists into steamvr home or the next game. The issue does go away if I exit XSOverlay.

I found I can fix the game to be responsive to inputs again by doing these steps: pressing the "Layout Mode" button on XSOverlay on my hand to hide all open windows, and then open and close the steamvr dashboard once. After that, the game responds to inputs again correctly, and I can press the Layout Mode button on XSOverlay to bring my windows back.

The only other steamvr overlay I use is OVR Advanced Settings. I believe I've had this issue once before with only XSOverlay active, but I'm not 100% sure about that. I've never had this issue with OVRAS alone; I used OVRAS by itself for a long time, and the first time I ever ran into this issue was the second day I used XSOverlay. I've run into this issue in both the SteamVR home and VRChat. I've run into this issue on multiple computers, both Windows 10 with Index controllers. (Headset is either Index or Vive.)

I'm not sure if there's anything specific I'm doing before the issue begins. When I use XSOverlay, almost always the first thing I do is attach a Discord window to my left hand and then I enable auto-hide and lock on the window. I leave the Layout Mode button enabled so the window is always ready to peek at. I wondered if maybe I'm occasionally accidentally pointing at and clicking on the Discord window without realizing it in a way which is causing my inputs to get locked to it, but that doesn't make much sense because when I interact with windows normally through XSOverlay, it doesn't block input events to the game.

I do not use the "input blocking" setting. I did try it out once but I didn't see any effect from it. It seems really strange that XSOverlay isn't capable of blocking inputs correctly when I have this setting on, but is capable of doing it spontaneously regardless of this setting. (Could this be related?)

I've attached an output log which I copied immediately after I ran into an instance of this issue and recovered from it.

[output_log.txt](https://github.com/Xiexe/XSOverlay-Issue-Tracker/files/5563203/output_log.-.Copy.txt)

**Comment by Xiexe** [comment]
I can't say I've ever run into this, all I can say is make sure that input blocking is actually turned off.

It's in the experimental tab in the settings. Due to some issues with the way I was loading new settings a user has never seen before up until recent beta builds, it may have defaulted to on. ( Based on the logs, it looks like that's what is happening )

I'd recommend also trying the beta branch, as it's updated a few things that were preventing settings from saving, preventing the tutorial from going away, and the new settings being loaded with incorrect defaults.

With input blocking, the way that it works is by taking priority over inputs that are bound on the controllers.

So, if it's turned on, and you pull a trigger, if it's bound in the overlays bindings, it will only go through to the overlay, and not the game. (That's just how valve implemented it)

It requires you to toggle layout mode off and back on again for it to start working, which is likely why it seemed spontaneous.

**Comment by Xiexe** [comment]
Found that there was indeed an issue with input blocking if you used the wrist overlays button to toggle layout mode.

This has been addressed and should make it to the live branch along with a bunch of other changes sometime Monday.
